# -*- mode: python ; coding: utf-8 -*-
"""PyInstaller spec for obj.Paper.

Build with `python scripts/build.py` rather than calling PyInstaller
directly — the helper script handles icon conversion (.ico / .icns) and
post-build packaging (.zip on Windows, .dmg on macOS).
"""

from __future__ import annotations

import os
import sys

# PyInstaller injects SPECPATH (directory containing this spec file) so we
# don't have to depend on __file__ being set.
ROOT = SPECPATH if "SPECPATH" in globals() else os.getcwd()
BRAND_PNG = os.path.join(ROOT, "obj.Paper Icon 64.png")
ASSETS_DIR = os.path.join(ROOT, "obj_paper", "assets")

# Per-OS icon source generated by scripts/build.py
if sys.platform == "win32":
    ICON_PATH = os.path.join(ASSETS_DIR, "icon.ico")
elif sys.platform == "darwin":
    ICON_PATH = os.path.join(ASSETS_DIR, "icon.icns")
else:
    ICON_PATH = BRAND_PNG  # Linux: PNG is fine for in-window icon

# datas: (src, dest-relative-to-bundle)
datas = [(BRAND_PNG, ".")]

# Heavy hidden imports — PyInstaller normally finds these via PyQt6/matplotlib
# hooks, but matplotlib's backend system and Pygments' lexer registry are
# dynamic enough that we pin a few essentials.
hiddenimports = [
    "matplotlib.backends.backend_agg",
    "PyQt6.QtPrintSupport",
    "PyQt6.QtSvg",
    "PyQt6.QtPdf",
    "PyQt6.QtPdfWidgets",
]

# Don't drag along stuff we don't use — keeps the bundle inside the 80–120 MB
# range spec.md §18 promises.
excludes = [
    "tkinter",
    "PyQt5",
    "PySide2",
    "PySide6",
    "IPython",
    "pytest",
    "notebook",
    "jupyter",
    "scipy",
    "pandas",
    "sympy",
    "test",
    "tests",
    "unittest",
]

block_cipher = None

a = Analysis(
    [os.path.join(ROOT, "obj_paper", "__main__.py")],
    pathex=[ROOT],
    binaries=[],
    datas=datas,
    hiddenimports=hiddenimports,
    hookspath=[],
    runtime_hooks=[],
    excludes=excludes,
    noarchive=False,
    cipher=block_cipher,
)

# Pygments lexers register lazily — collect them all so syntax highlighting
# for every supported language survives freezing.
try:
    from PyInstaller.utils.hooks import collect_submodules
    a.hiddenimports += collect_submodules("pygments.lexers")
    a.hiddenimports += collect_submodules("pygments.styles")
    a.hiddenimports += collect_submodules("pygments.formatters")
except Exception:
    pass

pyz = PYZ(a.pure, a.zipped_data, cipher=block_cipher)

exe = EXE(
    pyz,
    a.scripts,
    [],
    exclude_binaries=True,   # one-folder mode
    name="obj.Paper",
    debug=False,
    bootloader_ignore_signals=False,
    strip=False,
    upx=False,                # UPX is unreliable on Qt DLLs
    console=False,            # GUI app — no terminal window
    disable_windowed_traceback=False,
    argv_emulation=False,
    target_arch=None,
    codesign_identity=None,
    entitlements_file=None,
    icon=ICON_PATH if os.path.exists(ICON_PATH) else None,
)

coll = COLLECT(
    exe,
    a.binaries,
    a.zipfiles,
    a.datas,
    strip=False,
    upx=False,
    upx_exclude=[],
    name="obj.Paper",
)

# macOS-only: wrap the COLLECT output in an .app bundle
if sys.platform == "darwin":
    app = BUNDLE(
        coll,
        name="obj.Paper.app",
        icon=ICON_PATH if os.path.exists(ICON_PATH) else None,
        bundle_identifier="com.lshift.objpaper",
        info_plist={
            "CFBundleShortVersionString": "1.0.0",
            "CFBundleVersion": "1.0.0",
            "CFBundleDisplayName": "obj.Paper",
            "CFBundleName": "obj.Paper",
            "LSMinimumSystemVersion": "12.0",
            "NSHighResolutionCapable": True,
            "NSPrincipalClass": "NSApplication",
            "NSRequiresAquaSystemAppearance": False,
        },
    )
